
# salesforce JWT Configuration
sf:
  consumerKey : "![vDmQpBxkxy1+xc0xZuvT7ewU4lheJSX3iNDeyu8jW2d9tB57bR6WQg6TgJO6EF/Y65jRyGV8B77W1soTeEbCNQ+ORAkBKURT9p4RL/nDMj/622lcWSqy8F4snkfZDy+n]"
  storePassword : "![lMIzNMqMfYjNrDJw/DzsyA==]"
  principal : "yogesh.mulchandani@minlopro.com.wipdev"
  tokenEndpoint : "https://test.salesforce.com/services/oauth2/token"

# Google Drive Token generator connector configuration
GDaccessToken:
   host : "oauth2.googleapis.com"
   
# Google Drive Token Generator Connector Credentials   
GDaccessTokenCred:
  client_id: "![1aU8pghApT4NTLSRTzmTAoxd1vHCqNTxDwpb4P1gaMys6NTTyLfpyYqFrBbTUpjlAyZ5jvsIybH+hcjWPH14E/vZOKv45ZhmdI6kiGZlbN8=]"    
  client_secret: "![nukoDKl3KYBJ5qWjplozxJpNpTif+oC8KCpL9cadMzXWwArMprtyNWeWhAu0PFf7]"
  refresh_token: "![g5zCJ4gqaH0lRe4z+8dFhlmOS0fG24Iv2zHIfb8BC+rkzTMqeh/7L731IBZCgHjJ3scAXnlJM13e9TxauWa9RHPYZCLJf9Gz5FyaJ+LU42cKyVB008bv+t1yOix3vTa30XGkzVcbnhjJSY9tHresXw==]"

# Google Drive Folders  connector configuration 
GDConnector:
  host: "www.googleapis.com"
  
# Name of the folder
drive:
  rootFolderName: "SalesforceTest"
  opportunityFolder: "OPPORTUNITY"
  projectFolder: "PROJECT"  
  
# Alphabet Folders ID
AplhabetID:
  firstfolder: "1L8iJUnxBcjXwqLpM5WMLxwqj8JtzzQlh"
  secondfolder: "1dS31wxJaHMyMyz6KII-EV5n85-Bap46I"
  thirdfolder: "11nthPazHGYs7L_JrvKAfvpgPrCuj0Z7E"
          
    